before_build:
  - dotnet restore

build_script:
  - dotnet build -c "Release" --no-restore
  - dotnet pack ./src/Otp.NET/Otp.NET.csproj --no-build -o ../dist  -c "Release"

test_script:
  - dotnet test --no-build

deploy: off

artifacts:
  - path: 'dist\*.nupkg'
